#!/usr/bin/env python3
"""
PDF生成器 v3.0 - 使用 fpdf2 (更好的Unicode支持)
解决中文乱码和重叠问题
"""
from fpdf2 import FPDF
from datetime import datetime
from pathlib import Path
import os


class ChinesePDF(FPDF):
    """支持中文的PDF生成器"""
    
    def __init__(self):
        super().__init__(orientation='portrait', unit='mm', format='A4')
        self.set_auto_page_break(auto=True, margin=15)
        
        self.margin_left = 15
        self.margin_right = 15
        self.margin_top = 15
        
        # 尝试加载中文字体
        self.chinese_font = None
        self._load_chinese_font()
    
    def _load_chinese_font(self):
        """加载中文字体"""
        font_paths = [
            '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc',
            '/usr/share/fonts/opentype/noto/NotoSansCJK-Light.ttc',
            '/usr/share/fonts/truetype/arphic/uming.ttc',
        ]
        
        for font_path in font_paths:
            if os.path.exists(font_path):
                try:
                    # fpdf2 使用 add_font 方法
                    self.add_font(font_path, 'NotoSans')
                    self.chinese_font = 'NotoSans'
                    print(f"Loaded font: {font_path}")
                    return
                except Exception as e:
                    print(f"Failed to load {font_path}: {e}")
        
        # 使用内置字体
        self.chinese_font = 'helvetica'
    
    def header(self):
        self.set_font(self.chinese_font if self.chinese_font else 'helvetica', '', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Quant Analysis Report', align='R')
        self.ln(5)
    
    def footer(self):
        self.set_font(self.chinese_font if self.chinese_font else 'helvetica', '', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')


def generate_quant_pdf(data: dict, output_path: str) -> str:
    """生成量化分析PDF报告"""
    
    pdf = ChinesePDF()
    pdf.add_page()
    
    # 标题
    pdf.set_font('helvetica', 'B', 20)
    pdf.set_text_color(26, 54, 93)
    pdf.cell(0, 15, 'Quant Analysis Report', align='C', new_y="NEXT")
    pdf.ln(5)
    
    # 日期
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Date: {data.get('date', datetime.now().strftime('%Y-%m-%d'))}", align='C', new_y="NEXT")
    pdf.ln(10)
    
    # 摘要部分
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_text_color(26, 54, 93)
    pdf.cell(0, 8, 'Summary', new_y="NEXT")
    pdf.set_draw_color(49, 130, 206)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 30, pdf.get_y())
    pdf.ln(3)
    
    # 摘要内容
    pdf.set_font('helvetica', '', 11)
    pdf.set_text_color(45, 55, 72)
    
    summary_items = data.get('summary', [])
    for item in summary_items:
        pdf.cell(0, 6, f"- {item}", new_y="NEXT")
    
    pdf.ln(8)
    
    # 信号部分
    if data.get('signals'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 54, 93)
        pdf.cell(0, 8, 'Trading Signals', new_y="NEXT")
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 45, pdf.get_y())
        pdf.ln(3)
        
        # 信号表格
        pdf.set_font('helvetica', 'B', 9)
        pdf.set_fill_color(26, 54, 93)
        pdf.set_text_color(255, 255, 255)
        
        # 表头
        pdf.cell(30, 8, 'Code', 1, 0, 'C', True)
        pdf.cell(25, 8, 'Signal', 1, 0, 'C', True)
        pdf.cell(25, 8, 'Probability', 1, 0, 'C', True)
        pdf.cell(30, 8, 'Name', 1, 0, 'C', True)
        pdf.ln()
        
        # 数据行
        pdf.set_font('helvetica', '', 9)
        pdf.set_text_color(45, 55, 72)
        
        for i, signal in enumerate(data.get('signals', [])[:10]):
            if i % 2 == 0:
                pdf.set_fill_color(247, 250, 252)
            else:
                pdf.set_fill_color(255, 255, 255)
            
            code = signal.get('code', '')
            signal_type = signal.get('signal', '')
            prob = signal.get('probability', '')
            name = signal.get('name', '')[:10]
            
            pdf.cell(30, 7, code, 1, 0, 'C', True)
            pdf.cell(25, 7, signal_type, 1, 0, 'C', True)
            pdf.cell(25, 7, f"{prob}%", 1, 0, 'C', True)
            pdf.cell(30, 7, name, 1, 0, 'C', True)
            pdf.ln()
    
    pdf.ln(10)
    
    # 备注
    pdf.set_font('helvetica', 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, "Generated by Unified Quant Analysis System. For reference only, not investment advice.")
    
    # 保存
    pdf.output(output_path)
    return output_path


if __name__ == '__main__':
    # 测试
    test_data = {
        'date': '2026-03-05',
        'summary': [
            'Total Stocks: 13',
            'Reliable: 13 (95%)',
            'Buy Signals: 0',
            'Sell Signals: 0',
            'Watch: 8'
        ],
        'signals': [
            {'code': '300199', 'signal': 'Watch', 'probability': '50', 'name': 'Hanyu'},
            {'code': '301381', 'signal': 'Watch', 'probability': '50', 'name': ''},
            {'code': '300628', 'signal': 'Watch', 'probability': '50', 'name': 'Yilian'},
            {'code': '300533', 'signal': 'Watch', 'probability': '50', 'name': 'Bingchuan'},
            {'code': '300251', 'signal': 'Watch', 'probability': '50', 'name': 'Guangxian'}
        ]
    }
    
    output = generate_quant_pdf(test_data, '/home/liujerry/reports/quant_v3_test.pdf')
    print(f"Generated: {output}")
